cc_binary(
    name = "day01",
    srcs = ["day01.cpp"],
    deps = [
        "//tools",
        "@abseil-cpp//absl/container:flat_hash_map",
        "@abseil-cpp//absl/strings",
    ],
)

cc_binary(
    name = "day02",
    srcs = ["day02.cpp"],
    deps = [
        "//tools",
        "@abseil-cpp//absl/strings",
    ],
)

cc_binary(
    name = "day03",
    srcs = ["day03.cpp"],
    deps = [
        "//tools",
        "@abseil-cpp//absl/strings",
    ],
)