package(default_visibility = ["//visibility:public"])

cc_library(
    name = "tools",
    hdrs = [
        "io.h",
        "log.h",
        "main.h",
    ],
    srcs = [
        "io.cpp",
        "log.cpp",
        "main.cpp",
    ]
)